name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04, windows-2022]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make fmt
      - run: make tidy
      - run: make vet
      - run: make test
      - run: make ztest
      - run: make release
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: build/brimcap-*.zip
      - if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/brimcap-*.zip
          file_glob: true
          overwrite: true
