name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: make fmt
      - run: make tidy
      - run: make vet
      - run: make test
      - run: make ztest
      - run: make release
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: build/brimcap-*.zip
      - if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: builds/brimcap-*.zip
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
